/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import DAO.CTHoaDonDAO;
//import Model.HoaDonThanhToan;
import DAO.CTHoaDonDAO1;
import DAO.HoaDonDAO1;
import DAO.LoaiMonDAO;
import DAO.MonAnDAO;
import DAO.PhieuDatDAO;
import Helper.DialogHelper;
import Helper.JdbcHelper;
import Model.CTHoaDon1;
import Model.LoaiMon;
import Model.MonAn;
import Model.NhanVien;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class HoaDonForm extends javax.swing.JFrame {

    /**
     * Creates new form HoaDon
     */
    private DefaultTableModel model;
    private DefaultTableModel model1;
    private List<LoaiMon> list;
    private List<CTHoaDon1> lst;
    int index = 0;
    private String a;
    private int vitri;
    private int MaPH;
    private int vitriMonAn;
    HoaDonDAO1 HDDao = new HoaDonDAO1();
    PhieuDatDAO PDDao = new PhieuDatDAO();
    LoaiMonDAO LMdao = new LoaiMonDAO();
    MonAnDAO MAdao = new MonAnDAO();
    CTHoaDonDAO1 CTHDDao = new CTHoaDonDAO1();

    public HoaDonForm() {
        initComponents();
        fillTable();
        lst = CTHDDao.getAll(MaHD);
        this.model = (DefaultTableModel) tblMonAn.getModel();
        this.model1 = (DefaultTableModel) tbl_HoaDon.getModel();
        list = LMdao.select();
//        LoadTableMeNu(MaHD);
        if (cbb_LoaiMon.getItemCount() > 0) {
            LoaiMon x = list.get(0);
            String MaLM = x.getMaLoaiMon();
            LoadTableMonAn(MaLM);
            fillComboBoxLoaiMon();
            LoadTableMeNu(MaHD);
        }

        LoadSoLuong();
        
    }
    Integer MaHD;

    HoaDonForm(Integer ID) {
        initComponents();
        MaHD = ID;
        fillTable();

        this.model = (DefaultTableModel) tblMonAn.getModel();
        this.model1 = (DefaultTableModel) tbl_HoaDon.getModel();
        LoadTableMeNu(MaHD);
        list = LMdao.select();
        if (cbb_LoaiMon.getItemCount() > 0) {
            LoaiMon x = list.get(0);
            String MaLM = x.getMaLoaiMon();
            LoadTableMonAn(MaLM);

        }
        fillComboBoxLoaiMon();
        LoadSoLuong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void fillTable() {
        try {
            String sql = "Select *\n"
                    + "from ((HoaDon inner join PhieuDat on HoaDon.MaPD=PhieuDat.MaPD)\n"
                    + "inner join ThongTinKH on ThongTinKH.MaKH = PhieuDat.MaKH)\n"
                    + "WHERE MaHD =?";
            ResultSet rs = JdbcHelper.executeQuery(sql, MaHD);
            while (rs.next()) {
                txt_TenKhach.setText(rs.getString("Hoten"));
                txt_SoDT.setText(rs.getString("SDT"));
                txt_SoNguoi.setText(String.valueOf(rs.getInt("SoNguoi")));
                txt_NgayAn.setText(String.valueOf(rs.getDate("DateBook")));

                MaPH = rs.getInt("MaPD");
                txt_MaHD.setText(String.valueOf(rs.getInt("MaHD")));
            }
        } catch (SQLException e) {
            e.printStackTrace();

        }
    }

    void fillComboBoxLoaiMon() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbb_LoaiMon.getModel();
        model.removeAllElements();
        try {
            List<LoaiMon> listLM = LMdao.select();
            if (!listLM.isEmpty()) {
                for (LoaiMon cd : listLM) {
                    model.addElement(cd);
                }
            }

        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private void LoadTableMonAn(String MaLoaiMon) {
        model.setRowCount(0);
        List<MonAn> lst = MAdao.getAll(MaLoaiMon);
        for (int i = 0; i < lst.size(); i++) {
            MonAn s = lst.get(i);
            Object[] obj = new Object[]{
                s.getMaMon(),
                s.getTenMon(),
                s.getGiaTien(),
                s.getGioiThieu(),};
            model.addRow(obj);
        }
    }

    private void LoadTableMeNu(int MaHD) {
        model1.setRowCount(0);
        lst = CTHDDao.getAll(MaHD);
        for (int i = 0; i < lst.size(); i++) {
            CTHoaDon1 s = lst.get(i);
            Object obj[] = new Object[7];

            obj[0] = model1.getRowCount() + 1;
            obj[1] = s.getTenMon();
            obj[2] = s.getGiaTien();
            obj[3] = s.getSoLuong();
            obj[4] = Double.parseDouble(s.getSoLuong() + "") * s.getGiaTien();
            obj[5] = s.getGhiChu();
            obj[6] = s.getTrangThaiMon();
            model1.addRow(obj);

        }
    }

    void editMonAn() {
        try {
            String MaMon = (String) tblMonAn.getValueAt(this.index, 0);
            MonAn model = MAdao.findbyID(MaMon);
            if (model != null) {
                this.setModelMonAn(model);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void setModelMonAn(MonAn model) {
        lb_TenMon.setText(model.getTenMon());
        lb_Giatien.setText(String.valueOf(model.getGiaTien()));
    }

    void clear() {
        lb_Giatien.setText("");
        lb_TenMon.setText("");
        txt_SoLuong.setText("");
        txt_GhiChu.setText("");
    }

    CTHoaDon1 getModel() {
        CTHoaDon1 model = new CTHoaDon1();
        model.setMaHD(Integer.parseInt(txt_MaHD.getText()));
        model.setSoBan(Integer.parseInt(txt_SoBan.getText()));
        model.setTenMon((lb_TenMon.getText()));
        model.setGhiChu(txt_GhiChu.getText());
        model.setTrangThaiMon("Chưa Lên");
        String tien = String.valueOf(tblMonAn.getValueAt(vitriMonAn, 2));
        model.setGiaTien(Double.parseDouble(tien));
        model.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
        return model;
    }

    CTHoaDon1 getModelUpdate() {
        CTHoaDon1 model = new CTHoaDon1();
        model.setMaHD(MaHD);
        model.setTenMon(tbl_HoaDon.getValueAt(vitri, 1).toString());
        model.setGhiChu(txt_GhiChu.getText());
        String tien = String.valueOf(tblMonAn.getValueAt(vitriMonAn, 2));
        model.setGiaTien(Double.parseDouble(tien));
        model.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
        return model;
    }

    CTHoaDon1 getModelLenMon() {
        CTHoaDon1 model = new CTHoaDon1();
        model.setMaHD(MaHD);
        model.setTenMon(tbl_HoaDon.getValueAt(vitri, 1).toString());
        model.setGhiChu(tbl_HoaDon.getValueAt(vitri, 5).toString());
        model.setTrangThaiMon("Đã Lên");
        model.setSoLuong(Integer.parseInt(tbl_HoaDon.getValueAt(vitri, 3).toString()));
        return model;
    }

    CTHoaDon1 getModelUpdateHuy() {
        CTHoaDon1 model = new CTHoaDon1();
        model.setTenMon(tbl_HoaDon.getValueAt(vitri, 1).toString());
        model.setMaHD(MaHD);
        model.setGhiChu("");
        model.setTrangThaiMon("Đã Hủy");
        String tien = String.valueOf(tbl_HoaDon.getValueAt(vitriMonAn, 4));
        model.setGiaTien(Double.parseDouble(tien));
      model.setSoLuong(Integer.parseInt(tbl_HoaDon.getValueAt(vitri, 3).toString()));
        return model;
    }

    void InsertMonAn() {
        CTHoaDon1 model = getModel();
        for (CTHoaDon1 x : lst) {
            String MaHD = String.valueOf(x.getMaHD() + "");
            String tenmon = x.getTenMon();
            String trangthai = x.getTrangThaiMon();
            if (MaHD.equals(txt_MaHD.getText()) && tenmon.equals(lb_TenMon.getText()) && trangthai.equals("Chưa Lên")) {
                DialogHelper.alert(this, "Món đã được gọi trước đó");
                return;
            }
        }
        try {
            CTHDDao.insert(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void UpdateSuaMon() {
        CTHoaDon1 model = getModelUpdate();
        try {
            CTHDDao.SuaMeNu(model);
            LoadTableMeNu(MaHD);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void UpdateHuy() {
        CTHoaDon1 model = getModelUpdateHuy();
        try {
            CTHDDao.update(model);
            LoadTableMeNu(MaHD);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void UpdateLenMon() {
        CTHoaDon1 model = getModelLenMon();
        try {
            CTHDDao.update(model);
            LoadTableMeNu(MaHD);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmenu = new javax.swing.JPopupMenu();
        mnLenMon = new javax.swing.JMenuItem();
        mnSua = new javax.swing.JMenuItem();
        mnXoa = new javax.swing.JMenuItem();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_TenMon = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbb_LoaiMon = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        lb_Giatien = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_SoNguoi = new javax.swing.JLabel();
        txt_TenKhach = new javax.swing.JLabel();
        txt_SoDT = new javax.swing.JLabel();
        txt_NgayAn = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_SoBan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnChuyen = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb_TongMon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_ChuaLen = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lb_DaLen = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lb_DaHuy = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        mnLenMon.setText("Lên món ăn");
        mnLenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLenMonActionPerformed(evt);
            }
        });
        pmenu.add(mnLenMon);

        mnSua.setText("Sửa Món Ăn");
        mnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuaActionPerformed(evt);
            }
        });
        pmenu.add(mnSua);

        mnXoa.setText("Hủy Món Ăn");
        mnXoa.setToolTipText("");
        mnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXoaActionPerformed(evt);
            }
        });
        pmenu.add(mnXoa);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel11.setText("Tên Món :");

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel12.setText("Giá Tiền:");

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel13.setText("Số Lượng:");

        lb_TenMon.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N

        txt_SoLuong.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel15.setText("Loại Món:");

        cbb_LoaiMon.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        cbb_LoaiMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_LoaiMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_LoaiMonItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel16.setText("Ghi Chú :");

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_GhiChu.setRows(5);
        jScrollPane3.setViewportView(txt_GhiChu);

        lb_Giatien.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lb_Giatien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SoLuong))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_LoaiMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Giatien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_TenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_TenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Giatien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cbb_LoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gọi Món");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Khách Hàng   :");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Số Điện Thoại:");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setText("Ngày      :");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel6.setText("Số Người     :");
        jLabel6.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel10.setText("Mã Hóa Đơn:");

        txt_SoNguoi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_SoNguoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_TenKhach.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_TenKhach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_SoDT.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_SoDT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txt_NgayAn.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_NgayAn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_NgayAn.setText("22/10/2002");

        txt_MaHD.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_MaHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_MaHD.setText("3");

        jLabel17.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel17.setText("Số Bàn    :");

        txt_SoBan.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_SoBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_SoBan.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_TenKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txt_SoDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_SoNguoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(txt_SoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_NgayAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_TenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txt_MaHD)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_SoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_SoDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_SoNguoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_NgayAn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        tblMonAn.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Món", "Tên Món", "Giá Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonAn.setRowHeight(30);
        tblMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonAnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMonAn);

        tbl_HoaDon.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Món", "Đơn Giá", "Số Lượng", "Thành Tiền", "Ghi Chú", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HoaDon.setComponentPopupMenu(pmenu);
        tbl_HoaDon.setRowHeight(30);
        jScrollPane1.setViewportView(tbl_HoaDon);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnChuyen.setBackground(new java.awt.Color(255, 255, 255));
        btnChuyen.setText("Thêm");
        btnChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenActionPerformed(evt);
            }
        });

        btn_Clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setText("Tổng:");

        lb_TongMon.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lb_TongMon.setText("0");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel8.setText("Chưa lên:");

        lb_ChuaLen.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lb_ChuaLen.setText("0");

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel14.setText("Đã Lên:");

        lb_DaLen.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lb_DaLen.setText("0");

        jLabel18.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel18.setText("Đã Hủy:");

        lb_DaHuy.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lb_DaHuy.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_TongMon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ChuaLen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_DaLen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_DaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_ChuaLen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_TongMon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_DaLen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_DaHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        btn_ThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(813, 813, 813)
                        .addComponent(btn_ThanhToan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbb_LoaiMonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_LoaiMonItemStateChanged
        try {
            if (cbb_LoaiMon.getItemCount() > 0) {
                int index = cbb_LoaiMon.getSelectedIndex();
                if (index == -1) {
                    return;
                }
                LoaiMon x = list.get(index);
                String MaLM = x.getMaLoaiMon();
                LoadTableMonAn(MaLM);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbb_LoaiMonItemStateChanged

    private void tblMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonAnMouseClicked
        if (evt.getClickCount() == 2) {
            this.index = tblMonAn.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.editMonAn();
            }
        }
    }//GEN-LAST:event_tblMonAnMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      if (Check() == false) {
            UpdateSuaMon();
            //        Double giaTien = Double.parseDouble(lb_Giatien.getText());
            //        String SoLuong = txt_SoLuong.getText();
            //        Double tien = Double.parseDouble(SoLuong) * giaTien;
            //        tbl_HoaDon.setValueAt(txt_SoLuong.getText(), vitri, 3);
            //        tbl_HoaDon.setValueAt(tien, vitri, 4);
            LoadTableMeNu(MaHD);
            LoadSoLuong();
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenActionPerformed
     if (Check() == false) {
            InsertMonAn();
            LoadSoLuong();
            //        String tenMon = lb_TenMon.getText();
            //        Double giaTien = Double.parseDouble(lb_Giatien.getText());
            //        String SoLuong = txt_SoLuong.getText();
            //        String gc = txt_GhiChu.getText();
            //        CTHDDao.LoadCTHoaDon(tbl_HoaDon, tenMon, giaTien, SoLuong, gc, "Chưa Lên");
            LoadTableMeNu(MaHD);
            clear();
        }


    }//GEN-LAST:event_btnChuyenActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        clear();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
       for (int i = 0; i < lst.size(); i++) {
            CTHoaDon1 s = lst.get(i);
            String a = String.valueOf(s.getMaHD());
            if (a.equalsIgnoreCase(txt_MaHD.getText()) && s.getTrangThaiMon().equalsIgnoreCase("Chưa Lên")) {
                DialogHelper.alert(this, "Món chưa lên hết, không thể thanh toán");
                return;

            }
        }
        Integer MaHD = Integer.valueOf(txt_MaHD.getText());
        new HoaDonTT(MaHD).setVisible(true);
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void mnLenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLenMonActionPerformed
        vitri = tbl_HoaDon.getSelectedRow();
        String TrangThai = tbl_HoaDon.getValueAt(vitri, 6).toString();
        if (TrangThai.equals("Đã Hủy") || TrangThai.equals("Đã Lên")) {
            DialogHelper.alert(this, "Bạn không thể sửa");
            return;
        }
        UpdateLenMon();
        LoadSoLuong();
    }//GEN-LAST:event_mnLenMonActionPerformed

    private void mnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuaActionPerformed
        //         tbl_HoaDon.clearSelection();
        vitri = tbl_HoaDon.getSelectedRow();
        String TrangThai = tbl_HoaDon.getValueAt(vitri, 6).toString();
        if (TrangThai.equals("Đã Hủy") || TrangThai.equals("Đã Lên")) {
            DialogHelper.alert(this, "Bạn không thể sửa");
            return;
        }

        lb_TenMon.setText(tbl_HoaDon.getValueAt(vitri, 1).toString());
        lb_Giatien.setText(tbl_HoaDon.getValueAt(vitri, 2).toString());
        String soluong = tbl_HoaDon.getValueAt(vitri, 3).toString();
        a = tbl_HoaDon.getValueAt(vitri, 1).toString();
    }//GEN-LAST:event_mnSuaActionPerformed

    private void mnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXoaActionPerformed

        vitri = tbl_HoaDon.getSelectedRow();
        String TrangThai = tbl_HoaDon.getValueAt(vitri, 6).toString();
        if (TrangThai.equals("Đã Hủy") || TrangThai.equals("Đã Lên")) {
            DialogHelper.alert(this, "Bạn không thể sửa");
            return;
        }
        UpdateHuy();
        LoadTableMeNu(MaHD);
        LoadSoLuong();
    }//GEN-LAST:event_mnXoaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new HomeNhaHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonForm().setVisible(true);
            }
        });
    }

    private void LoadSoLuong() {
        try {
            String sql = "Select Sum(SoLuong) as A\n"
                    + "from CTHoaDon \n"
                    + "WHERE MaHD = ? and TrangThaiMon =N'Chưa Lên'";
            ResultSet rs = JdbcHelper.executeQuery(sql, MaHD);
            while (rs.next()) {
                String a = String.valueOf(rs.getInt("A"));
                lb_ChuaLen.setText(a);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            String sql = "Select Sum(SoLuong) as A\n"
                    + "from CTHoaDon \n"
                    + "WHERE MaHD = ? ";
            ResultSet rs = JdbcHelper.executeQuery(sql, MaHD);
            while (rs.next()) {
                String a = String.valueOf(rs.getInt("A"));
                lb_TongMon.setText(a);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            String sql1 = "Select Sum(SoLuong) as A\n"
                    + "from CTHoaDon \n"
                    + "WHERE MaHD = ? and TrangThaiMon =N'Đã Lên'";

            ResultSet rs = JdbcHelper.executeQuery(sql1, MaHD);
            while (rs.next()) {
                String a = String.valueOf(rs.getInt("A"));
                lb_DaLen.setText(a);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            String sql2 = "Select Sum(SoLuong) as A\n"
                    + "from CTHoaDon \n"
                    + "WHERE MaHD = ? and TrangThaiMon = N'Đã Hủy'";
            ResultSet rs = JdbcHelper.executeQuery(sql2, MaHD);
            while (rs.next()) {
                String a = String.valueOf(rs.getInt("A"));
                lb_DaHuy.setText(a);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public boolean Check() {
        Pattern sl = Pattern.compile("[0-9]");
        try {
            if (lb_TenMon.getText().equals("")) {
                DialogHelper.alert(this, "Mời bạn chọn món");
                return true;
            } else if (txt_SoLuong.getText().equals("")) {
                DialogHelper.alert(this, "Mời bạn ghi số lượng");
                return true;
            } else if (!sl.matcher(txt_SoLuong.getText()).find()) {
                DialogHelper.alert(this, "Số Lượng Không hợp lệ");
                return true;
            } else if (txt_GhiChu.getText().equals("")) {
                DialogHelper.alert(this, "Mời bạn ghi ghi chú");
                return true;
            }
        } catch (Exception e) {

        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyen;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JComboBox<String> cbb_LoaiMon;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_ChuaLen;
    private javax.swing.JLabel lb_DaHuy;
    private javax.swing.JLabel lb_DaLen;
    private javax.swing.JLabel lb_Giatien;
    private javax.swing.JLabel lb_TenMon;
    private javax.swing.JLabel lb_TongMon;
    private javax.swing.JMenuItem mnLenMon;
    private javax.swing.JMenuItem mnSua;
    private javax.swing.JMenuItem mnXoa;
    private javax.swing.JPopupMenu pmenu;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JLabel txt_MaHD;
    private javax.swing.JLabel txt_NgayAn;
    private javax.swing.JLabel txt_SoBan;
    private javax.swing.JLabel txt_SoDT;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JLabel txt_SoNguoi;
    private javax.swing.JLabel txt_TenKhach;
    // End of variables declaration//GEN-END:variables
}
