/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.KhachHangDAO;
import DAO.TaiKhoanKHDAO;
import Helper.DialogHelper;
import Model.KhachHang;
import Model.TaiKhoanKH;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class QuenMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau() {
        initComponents();
        setLocationRelativeTo(null);
        txt_TaiKhoan.setForeground(Color.GRAY);
        txt_Phone.setForeground(Color.GRAY);
        ImageIcon logo = new ImageIcon("src/Logo/LogoNH.png");
        lb_Logo.setIcon(logo);
    }
    KhachHangDAO dao = new KhachHangDAO();
    TaiKhoanKHDAO tkkh = new TaiKhoanKHDAO();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private  void QuenMK(){
        String us = txt_TaiKhoan.getText();
        String phone = txt_Phone.getText();
        try {
            KhachHang kh = dao.findById(us);
            if (kh != null) {
                String phone2 = kh.getSdt();
                if (phone.equals(phone2)) {
                    update();
                }else{
                    DialogHelper.alert(this, "Sai số điện thoại");
                }
            }else{
               DialogHelper.alert(this, "Sai tài khoản ");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    TaiKhoanKH getModel(){
        int len = 6;
        String kitu = "1234567890";
//        qwertyuiopasdfghjklmnbvcxzQWERTYUIOPLKJHGFDSAZXCVBNM
        StringBuilder st = new StringBuilder();
        Random rd = new Random();
        while (0<len--) {            
            st.append(kitu.charAt(rd.nextInt(kitu.length())));
        }
        TaiKhoanKH model = new TaiKhoanKH();
        model.setUsername(txt_TaiKhoan.getText());
        model.setPass(st.toString());
        DialogHelper.alert(this,"Mật khẩu mới của bạn là:" +st.toString());
        return model;
    }
    void update(){
        TaiKhoanKH model =getModel();
        try {
            tkkh.update(model);
        } catch (Exception e) {
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_TaiKhoan = new javax.swing.JTextField();
        txt_Phone = new javax.swing.JTextField();
        btn_Gui = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_DN = new javax.swing.JLabel();
        lb_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quên mật khẩu");

        txt_TaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_TaiKhoan.setText("Tài khoản");
        txt_TaiKhoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TaiKhoanFocusGained(evt);
            }
        });

        txt_Phone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_Phone.setText("Số điện thoại");
        txt_Phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PhoneFocusGained(evt);
            }
        });

        btn_Gui.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btn_Gui.setText("Gửi");
        btn_Gui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Quay lại");

        lb_DN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_DN.setText("Đăng nhập");
        lb_DN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_DNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lb_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Gui, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_DN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Gui, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_DN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuiActionPerformed
       QuenMK();
    }//GEN-LAST:event_btn_GuiActionPerformed

    private void txt_TaiKhoanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TaiKhoanFocusGained
    txt_TaiKhoan.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txt_TaiKhoan.getText().equals("Tài khoản")) {
                    txt_TaiKhoan.setText("");
                    txt_TaiKhoan.setForeground(Color.BLACK);
                } else {
                    txt_TaiKhoan.selectAll();
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txt_TaiKhoan.getText().equals("")) {
                    txt_TaiKhoan.setText("Tài khoản");
                    txt_TaiKhoan.setForeground(Color.GRAY);
                }
            }
        });
    }//GEN-LAST:event_txt_TaiKhoanFocusGained

    private void txt_PhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PhoneFocusGained
          txt_Phone.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txt_Phone.getText().equals("Số điện thoại")) {
                    txt_Phone.setText("");
                    txt_Phone.setForeground(Color.BLACK);
                } else {
                    txt_Phone.selectAll();
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (txt_Phone.getText().equals("")) {
                    txt_Phone.setText("Số điện thoại");
                    txt_Phone.setForeground(Color.GRAY);
                }
            }
        });
    }//GEN-LAST:event_txt_PhoneFocusGained

    private void lb_DNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_DNMouseClicked
        Login_KH lg = new Login_KH();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_lb_DNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Gui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_DN;
    private javax.swing.JLabel lb_Logo;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_TaiKhoan;
    // End of variables declaration//GEN-END:variables
}
