/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.KhachHangDAO;
import Helper.DateHelper;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Model.KhachHang;
import Model.PhieuDat;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Hi
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblHeaderTenNhaHang = new javax.swing.JLabel();
        pnFooter = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        pnMenuItem = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        btnDatBan = new javax.swing.JPanel();
        lblDatBan = new javax.swing.JLabel();
        btnDonDat = new javax.swing.JPanel();
        lblDondat = new javax.swing.JLabel();
        btnDanhGia = new javax.swing.JPanel();
        lblDanhGia = new javax.swing.JLabel();
        pnDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        pnNhan = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblTenNH = new javax.swing.JLabel();
        lblTenNhaHang = new javax.swing.JLabel();
        pnUser = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        lblNgay = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();
        pnGiaoDien = new javax.swing.JPanel();
        pnMenuNgang = new javax.swing.JPanel();
        lblThongBao = new javax.swing.JLabel();
        lblXemThem = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        LayerGiaoDien = new javax.swing.JLayeredPane();
        pnXemThem = new javax.swing.JPanel();
        pnDangNhap = new javax.swing.JPanel();
        lblDangNhap = new javax.swing.JLabel();
        pnDangXuatXT = new javax.swing.JPanel();
        lblDangXuatXT = new javax.swing.JLabel();
        pnDoiMK = new javax.swing.JPanel();
        lblDoiMK = new javax.swing.JLabel();
        pnThoat = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        pnHome = new javax.swing.JPanel();
        lblLoiChao = new javax.swing.JLabel();
        pnDatBan = new javax.swing.JPanel();
        pnGDDatBan = new javax.swing.JPanel();
        pnLeftDB = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnRightDB = new javax.swing.JPanel();
        txtNgayDat = new javax.swing.JTextField();
        txtSoNguoi = new javax.swing.JTextField();
        btnDatBanNgay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        cboTimeBook = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnQLTaiKhoan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTTUser = new javax.swing.JTextField();
        txtTTHoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTTNgaySinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtTTSDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTTEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCapNhatTT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblHeaderTenNhaHang.setBackground(new java.awt.Color(153, 153, 255));
        lblHeaderTenNhaHang.setFont(new java.awt.Font("Monospaced", 3, 36)); // NOI18N
        lblHeaderTenNhaHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTenNhaHang.setText("NHÀ HÀNG TÁM TÁM");
        lblHeaderTenNhaHang.setOpaque(true);

        pnFooter.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout pnFooterLayout = new javax.swing.GroupLayout(pnFooter);
        pnFooter.setLayout(pnFooterLayout);
        pnFooterLayout.setHorizontalGroup(
            pnFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        pnFooterLayout.setVerticalGroup(
            pnFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        pnMenu.setBackground(new java.awt.Color(204, 204, 204));

        pnMenuItem.setBackground(new java.awt.Color(255, 255, 255));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));

        lblHome.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/home1.png"))); // NOI18N
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        btnDatBan.setBackground(new java.awt.Color(255, 255, 255));

        lblDatBan.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDatBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/datban1.png"))); // NOI18N
        lblDatBan.setText("Đặt bàn");
        lblDatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatBanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnDatBanLayout = new javax.swing.GroupLayout(btnDatBan);
        btnDatBan.setLayout(btnDatBanLayout);
        btnDatBanLayout.setHorizontalGroup(
            btnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDatBanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDatBanLayout.setVerticalGroup(
            btnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        btnDonDat.setBackground(new java.awt.Color(255, 255, 255));

        lblDondat.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDondat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDondat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/phieudat1.png"))); // NOI18N
        lblDondat.setText("Đơn đặt");
        lblDondat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDondatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnDonDatLayout = new javax.swing.GroupLayout(btnDonDat);
        btnDonDat.setLayout(btnDonDatLayout);
        btnDonDatLayout.setHorizontalGroup(
            btnDonDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDonDatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDondat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDonDatLayout.setVerticalGroup(
            btnDonDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDondat, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        btnDanhGia.setBackground(new java.awt.Color(255, 255, 255));

        lblDanhGia.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDanhGia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDanhGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/danhgia1.png"))); // NOI18N
        lblDanhGia.setText("Đánh giá");
        lblDanhGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDanhGiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnDanhGiaLayout = new javax.swing.GroupLayout(btnDanhGia);
        btnDanhGia.setLayout(btnDanhGiaLayout);
        btnDanhGiaLayout.setHorizontalGroup(
            btnDanhGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDanhGiaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDanhGiaLayout.setVerticalGroup(
            btnDanhGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDanhGia, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        pnDangXuat.setBackground(new java.awt.Color(255, 255, 255));

        lblDangXuat.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/dangxuat1.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDangXuatLayout = new javax.swing.GroupLayout(pnDangXuat);
        pnDangXuat.setLayout(pnDangXuatLayout);
        pnDangXuatLayout.setHorizontalGroup(
            pnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDangXuatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDangXuatLayout.setVerticalGroup(
            pnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnNhan.setBackground(new java.awt.Color(220, 204, 255));

        btnLogin.setBackground(new java.awt.Color(153, 153, 255));
        btnLogin.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblTenNH.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblTenNH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNH.setText("RESTAURANT");

        lblTenNhaHang.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lblTenNhaHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNhaHang.setText("TÁM TÁM");

        javax.swing.GroupLayout pnNhanLayout = new javax.swing.GroupLayout(pnNhan);
        pnNhan.setLayout(pnNhanLayout);
        pnNhanLayout.setHorizontalGroup(
            pnNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenNH, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(lblTenNhaHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnNhanLayout.setVerticalGroup(
            pnNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenNhaHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnMenuItemLayout = new javax.swing.GroupLayout(pnMenuItem);
        pnMenuItem.setLayout(pnMenuItemLayout);
        pnMenuItemLayout.setHorizontalGroup(
            pnMenuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDonDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDanhGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMenuItemLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuItemLayout.setVerticalGroup(
            pnMenuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuItemLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDonDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pnUser.setBackground(new java.awt.Color(255, 255, 255));

        btnUser.setBackground(new java.awt.Color(255, 255, 255));
        btnUser.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        btnUser.setText("Username");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        lblNgay.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/lich1.png"))); // NOI18N
        lblNgay.setText("dd/mm/yyyy");

        lblGio.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblGio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/dongho2.png"))); // NOI18N
        lblGio.setText("hh:mm:ss");

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGroup(pnUserLayout.createSequentialGroup()
                        .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgay)
                            .addComponent(lblGio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenuItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnMenuItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnGiaoDien.setBackground(new java.awt.Color(255, 255, 255));

        pnMenuNgang.setBackground(new java.awt.Color(255, 255, 255));

        lblThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/chuongtb.png"))); // NOI18N

        lblXemThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/down.png"))); // NOI18N
        lblXemThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXemThemMouseClicked(evt);
            }
        });

        lblTen.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/use1.png"))); // NOI18N
        lblTen.setText("Name");
        lblTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenMouseClicked(evt);
            }
        });

        lblThoat.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/off.png"))); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnMenuNgangLayout = new javax.swing.GroupLayout(pnMenuNgang);
        pnMenuNgang.setLayout(pnMenuNgangLayout);
        pnMenuNgangLayout.setHorizontalGroup(
            pnMenuNgangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuNgangLayout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblXemThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnMenuNgangLayout.setVerticalGroup(
            pnMenuNgangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongBao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblXemThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LayerGiaoDien.setBackground(new java.awt.Color(255, 255, 255));

        pnXemThem.setBackground(new java.awt.Color(255, 255, 255));

        pnDangNhap.setBackground(new java.awt.Color(240, 240, 255));

        lblDangNhap.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key.png"))); // NOI18N
        lblDangNhap.setText("Đăng nhập");
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDangNhapLayout = new javax.swing.GroupLayout(pnDangNhap);
        pnDangNhap.setLayout(pnDangNhapLayout);
        pnDangNhapLayout.setHorizontalGroup(
            pnDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDangNhapLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDangNhapLayout.setVerticalGroup(
            pnDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnDangXuatXT.setBackground(new java.awt.Color(240, 240, 255));

        lblDangXuatXT.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDangXuatXT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDangXuatXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/dangxuat1.png"))); // NOI18N
        lblDangXuatXT.setText("Đăng xuất");

        javax.swing.GroupLayout pnDangXuatXTLayout = new javax.swing.GroupLayout(pnDangXuatXT);
        pnDangXuatXT.setLayout(pnDangXuatXTLayout);
        pnDangXuatXTLayout.setHorizontalGroup(
            pnDangXuatXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDangXuatXTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDangXuatXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDangXuatXTLayout.setVerticalGroup(
            pnDangXuatXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuatXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnDoiMK.setBackground(new java.awt.Color(240, 240, 255));

        lblDoiMK.setBackground(new java.awt.Color(240, 240, 255));
        lblDoiMK.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        lblDoiMK.setText("Đổi mật khẩu");
        lblDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnDoiMKLayout = new javax.swing.GroupLayout(pnDoiMK);
        pnDoiMK.setLayout(pnDoiMKLayout);
        pnDoiMKLayout.setHorizontalGroup(
            pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDoiMKLayout.setVerticalGroup(
            pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoiMK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pnThoat.setBackground(new java.awt.Color(240, 240, 255));

        lblExit.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        lblExit.setText("Thoát");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnThoatLayout = new javax.swing.GroupLayout(pnThoat);
        pnThoat.setLayout(pnThoatLayout);
        pnThoatLayout.setHorizontalGroup(
            pnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        pnThoatLayout.setVerticalGroup(
            pnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnXemThemLayout = new javax.swing.GroupLayout(pnXemThem);
        pnXemThem.setLayout(pnXemThemLayout);
        pnXemThemLayout.setHorizontalGroup(
            pnXemThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDangXuatXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDoiMK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnXemThemLayout.setVerticalGroup(
            pnXemThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXemThemLayout.createSequentialGroup()
                .addComponent(pnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnDangXuatXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnHome.setBackground(new java.awt.Color(255, 255, 255));

        lblLoiChao.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        lblLoiChao.setText("Hi, Wellcome back!");

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoiChao, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addComponent(lblLoiChao)
                .addContainerGap(646, Short.MAX_VALUE))
        );

        pnDatBan.setBackground(new java.awt.Color(255, 255, 255));

        pnGDDatBan.setBackground(new java.awt.Color(150, 150, 255));

        pnLeftDB.setBackground(new java.awt.Color(150, 150, 255));
        pnLeftDB.setToolTipText("");

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblTitle.setText("Đặt bàn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("_____");

        javax.swing.GroupLayout pnLeftDBLayout = new javax.swing.GroupLayout(pnLeftDB);
        pnLeftDB.setLayout(pnLeftDBLayout);
        pnLeftDBLayout.setHorizontalGroup(
            pnLeftDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftDBLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(pnLeftDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnLeftDBLayout.setVerticalGroup(
            pnLeftDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftDBLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lblTitle)
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnRightDB.setBackground(new java.awt.Color(255, 255, 255));

        txtNgayDat.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtNgayDat.setForeground(new java.awt.Color(153, 153, 153));
        txtNgayDat.setText("dd/mm/yyyy");
        txtNgayDat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNgayDatFocusGained(evt);
            }
        });
        txtNgayDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayDatMouseClicked(evt);
            }
        });

        txtSoNguoi.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtSoNguoi.setForeground(new java.awt.Color(153, 153, 153));
        txtSoNguoi.setText("Số người");
        txtSoNguoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoNguoiFocusGained(evt);
            }
        });
        txtSoNguoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoNguoiMouseClicked(evt);
            }
        });

        btnDatBanNgay.setBackground(new java.awt.Color(255, 255, 255));
        btnDatBanNgay.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        btnDatBanNgay.setForeground(new java.awt.Color(150, 150, 255));
        btnDatBanNgay.setText("Đặt bàn ngay");
        btnDatBanNgay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnDatBanNgayFocusGained(evt);
            }
        });
        btnDatBanNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatBanNgayMouseClicked(evt);
            }
        });
        btnDatBanNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatBanNgayActionPerformed(evt);
            }
        });

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        txtGhiChu.setLineWrap(true);
        txtGhiChu.setRows(5);
        txtGhiChu.setText("Ghi chú");
        txtGhiChu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGhiChuFocusGained(evt);
            }
        });
        txtGhiChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGhiChuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtGhiChu);

        cboTimeBook.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        cboTimeBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Date.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clock.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User group.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Notes.png"))); // NOI18N

        javax.swing.GroupLayout pnRightDBLayout = new javax.swing.GroupLayout(pnRightDB);
        pnRightDB.setLayout(pnRightDBLayout);
        pnRightDBLayout.setHorizontalGroup(
            pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightDBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDatBanNgay)
                    .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(txtNgayDat)
                        .addComponent(txtSoNguoi)
                        .addComponent(cboTimeBook, 0, 293, Short.MAX_VALUE)))
                .addGap(74, 74, 74))
        );
        pnRightDBLayout.setVerticalGroup(
            pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightDBLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTimeBook, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoNguoi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnRightDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDatBanNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnGDDatBanLayout = new javax.swing.GroupLayout(pnGDDatBan);
        pnGDDatBan.setLayout(pnGDDatBanLayout);
        pnGDDatBanLayout.setHorizontalGroup(
            pnGDDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGDDatBanLayout.createSequentialGroup()
                .addComponent(pnLeftDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnRightDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnGDDatBanLayout.setVerticalGroup(
            pnGDDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLeftDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGDDatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRightDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnDatBanLayout = new javax.swing.GroupLayout(pnDatBan);
        pnDatBan.setLayout(pnDatBanLayout);
        pnDatBanLayout.setHorizontalGroup(
            pnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGDDatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnDatBanLayout.setVerticalGroup(
            pnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDatBanLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pnGDDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THÔNG TIN CÁ NHÂN");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel7.setText("Username:");

        txtTTUser.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N

        txtTTHoTen.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel8.setText("Họ tên:");

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel9.setText("Giới tính:");

        txtTTNgaySinh.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel10.setText("Ngày sinh:");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        rdoNu.setText("Nữ");

        txtTTSDT.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel11.setText("Số điện thoại:");

        txtTTEmail.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jLabel12.setText("Email:");

        btnCapNhatTT.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhatTT.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        btnCapNhatTT.setText("Cập nhật");
        btnCapNhatTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnQLTaiKhoanLayout = new javax.swing.GroupLayout(pnQLTaiKhoan);
        pnQLTaiKhoan.setLayout(pnQLTaiKhoanLayout);
        pnQLTaiKhoanLayout.setHorizontalGroup(
            pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnQLTaiKhoanLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnQLTaiKhoanLayout.createSequentialGroup()
                        .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTTHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addComponent(txtTTNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addComponent(txtTTSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addComponent(txtTTUser))
                    .addComponent(btnCapNhatTT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pnQLTaiKhoanLayout.setVerticalGroup(
            pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLTaiKhoanLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTTUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnQLTaiKhoanLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTTNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTTHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTTSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(pnQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnCapNhatTT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        LayerGiaoDien.setLayer(pnXemThem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerGiaoDien.setLayer(pnHome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerGiaoDien.setLayer(pnDatBan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayerGiaoDien.setLayer(pnQLTaiKhoan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayerGiaoDienLayout = new javax.swing.GroupLayout(LayerGiaoDien);
        LayerGiaoDien.setLayout(LayerGiaoDienLayout);
        LayerGiaoDienLayout.setHorizontalGroup(
            LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerGiaoDienLayout.createSequentialGroup()
                    .addGap(0, 541, Short.MAX_VALUE)
                    .addComponent(pnXemThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnDatBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayerGiaoDienLayout.setVerticalGroup(
            LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayerGiaoDienLayout.createSequentialGroup()
                    .addComponent(pnXemThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 488, Short.MAX_VALUE)))
            .addGroup(LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayerGiaoDienLayout.createSequentialGroup()
                    .addGap(0, 35, Short.MAX_VALUE)
                    .addComponent(pnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(LayerGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnGiaoDienLayout = new javax.swing.GroupLayout(pnGiaoDien);
        pnGiaoDien.setLayout(pnGiaoDienLayout);
        pnGiaoDienLayout.setHorizontalGroup(
            pnGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenuNgang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LayerGiaoDien))
        );
        pnGiaoDienLayout.setVerticalGroup(
            pnGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaoDienLayout.createSequentialGroup()
                .addComponent(pnMenuNgang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 671, Short.MAX_VALUE))
            .addGroup(pnGiaoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaoDienLayout.createSequentialGroup()
                    .addGap(0, 36, Short.MAX_VALUE)
                    .addComponent(LayerGiaoDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnGiaoDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblHeaderTenNhaHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
            .addComponent(pnFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeaderTenNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pnGiaoDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblHeaderTenNhaHang.getAccessibleContext().setAccessibleName("TÁMTÁM");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon hinh = new ImageIcon("src/Logo/use.png");
        Image im = hinh.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(50, 47, im.SCALE_SMOOTH));
        btnUser.setIcon(icon);
        lblDangXuatXT.setBackground(Color.white);
        pnHome.setVisible(true);
        pnXemThem.setVisible(false);
        pnDatBan.setVisible(false);
        pnQLTaiKhoan.setVisible(false);
        btnHome.setBackground(new java.awt.Color(150, 150, 255));
    }//GEN-LAST:event_formWindowOpened

    private void lblXemThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXemThemMouseClicked

        if (evt.getClickCount() == 1) {
            ImageIcon icon = new ImageIcon("src/Logo/down.png");
            lblXemThem.setIcon(icon);
            pnXemThem.setVisible(false);
        } else {
            ImageIcon icon = new ImageIcon("src/Logo/up.png");
            lblXemThem.setIcon(icon);
            pnXemThem.setVisible(true);
//            pnHome.setVisible(false);
//            pnDatBan.setVisible(false);
//            pnXemNDChiTiet.setVisible(false);
//            pnQLTaiKhoan.setVisible(false);
        }

    }//GEN-LAST:event_lblXemThemMouseClicked

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        if (DialogHelper.confirm(pnGiaoDien, "Bạn có muốn thoát chương trình không?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        if (DialogHelper.confirm(pnGiaoDien, "Bạn có muốn thoát chương trình không?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        if (ShareHelper.USERkh != null) {
            DialogHelper.alert(this, "Bạn đang online! \nĐể đăng nhập vào tài khoản khác hãy đăng xuất trước.");
        } else {
            new Login_KH().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        ShareHelper.logoff1();
        new Login_KH().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (ShareHelper.USERkh != null) {
            DialogHelper.alert(this, "Bạn đang online! \nĐể đăng nhập vào tài khoản khác hãy đăng xuất trước.");
        } else {
            new Login_KH().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtNgayDatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgayDatFocusGained
        txtNgayDat.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                txtNgayDat.setBackground(new java.awt.Color(255, 255, 255));
                if (txtNgayDat.getText().equals("")) {
                    txtNgayDat.setText("dd/mm/yyyy");
                    txtNgayDat.setForeground(Color.GRAY);
                }
            }
        });
    }//GEN-LAST:event_txtNgayDatFocusGained

    private void txtNgayDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayDatMouseClicked
        txtNgayDat.setBackground(new java.awt.Color(220, 204, 255));
        if (txtNgayDat.getText().equals("dd/mm/yyyy")) {
            txtNgayDat.setText("");
            txtNgayDat.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNgayDatMouseClicked

    private void txtSoNguoiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoNguoiFocusGained
        txtSoNguoi.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                txtSoNguoi.setBackground(new java.awt.Color(255, 255, 255));
                if (txtSoNguoi.getText().equals("")) {
                    txtSoNguoi.setText("Số người");
                    txtSoNguoi.setForeground(Color.GRAY);
                }
            }
        });
    }//GEN-LAST:event_txtSoNguoiFocusGained

    private void txtSoNguoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoNguoiMouseClicked
        txtSoNguoi.setBackground(new java.awt.Color(220, 204, 255));
        if (txtSoNguoi.getText().equals("Số người")) {
            txtSoNguoi.setText("");
            txtSoNguoi.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSoNguoiMouseClicked

    private void btnDatBanNgayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDatBanNgayFocusGained
        btnDatBan.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                btnDatBan.setBackground(new java.awt.Color(255, 255, 255));
                btnDatBan.setForeground(new java.awt.Color(150, 150, 255));

            }
        });
    }//GEN-LAST:event_btnDatBanNgayFocusGained

    private void btnDatBanNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatBanNgayMouseClicked
        btnDatBan.setBackground(new java.awt.Color(150, 150, 255));
        btnDatBan.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDatBanNgayMouseClicked

    private void btnDatBanNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatBanNgayActionPerformed

    }//GEN-LAST:event_btnDatBanNgayActionPerformed

    private void txtGhiChuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChuFocusGained
        txtGhiChu.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

            }

            @Override
            public void focusLost(FocusEvent e) {
                txtGhiChu.setBackground(new java.awt.Color(255, 255, 255));
                txtGhiChu.setForeground(new java.awt.Color(150, 150, 255));

            }
        });
    }//GEN-LAST:event_txtGhiChuFocusGained

    private void txtGhiChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGhiChuMouseClicked
        if (txtGhiChu.getText().equals("Ghi chú")) {
            txtGhiChu.setText("");
            txtGhiChu.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtGhiChuMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        btnHome.setBackground(new java.awt.Color(150, 150, 255));
        btnDatBan.setBackground(Color.WHITE);
        btnDonDat.setBackground(Color.WHITE);
        btnDanhGia.setBackground(Color.WHITE);
        pnHome.setVisible(true);
        pnDatBan.setVisible(false);
        pnXemThem.setVisible(false);
        pnQLTaiKhoan.setVisible(false);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblDatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatBanMouseClicked
        btnHome.setBackground(Color.WHITE);
        btnDatBan.setBackground(new java.awt.Color(150, 150, 255));
        btnDonDat.setBackground(Color.WHITE);
        btnDanhGia.setBackground(Color.WHITE);
        pnHome.setVisible(false);
        pnXemThem.setVisible(false);
        pnDatBan.setVisible(true);
        pnQLTaiKhoan.setVisible(false);
    }//GEN-LAST:event_lblDatBanMouseClicked

    private void lblDondatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDondatMouseClicked
        btnHome.setBackground(Color.WHITE);
        btnDatBan.setBackground(Color.WHITE);
        btnDonDat.setBackground(new java.awt.Color(150, 150, 255));
        btnDanhGia.setBackground(Color.WHITE);
        pnHome.setVisible(false);
        pnXemThem.setVisible(false);
        pnDatBan.setVisible(false);
        pnQLTaiKhoan.setVisible(false);
    }//GEN-LAST:event_lblDondatMouseClicked

    private void lblDanhGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhGiaMouseClicked
        btnHome.setBackground(Color.WHITE);
        btnDatBan.setBackground(Color.WHITE);
        btnDonDat.setBackground(Color.WHITE);
        btnDanhGia.setBackground(new java.awt.Color(150, 150, 255));
        pnHome.setVisible(false);
        pnXemThem.setVisible(false);
        pnDatBan.setVisible(false);
        pnQLTaiKhoan.setVisible(false);
    }//GEN-LAST:event_lblDanhGiaMouseClicked

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        //btnUser.setBackground(new java.awt.Color(150, 150, 255));
        if (ShareHelper.USERkh != null) {
            btnHome.setBackground(Color.WHITE);
            btnDatBan.setBackground(Color.WHITE);
            btnDonDat.setBackground(Color.WHITE);
            btnDanhGia.setBackground(Color.WHITE);
            pnHome.setVisible(false);
            pnXemThem.setVisible(false);
            pnDatBan.setVisible(false);
            pnQLTaiKhoan.setVisible(true);
        } else {
            DialogHelper.alert(pnQLTaiKhoan, "Vui lòng đăng nhập để sử dụng chức năng này");
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void lblTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenMouseClicked
        if (ShareHelper.USERkh != null) {
            btnHome.setBackground(Color.WHITE);
            btnDatBan.setBackground(Color.WHITE);
            btnDonDat.setBackground(Color.WHITE);
            btnDanhGia.setBackground(Color.WHITE);
            pnHome.setVisible(false);
            pnXemThem.setVisible(false);
            pnDatBan.setVisible(false);
            pnQLTaiKhoan.setVisible(true);
        } else {
            DialogHelper.alert(pnQLTaiKhoan, "Vui lòng đăng nhập để sử dụng chức năng này");
        }
    }//GEN-LAST:event_lblTenMouseClicked

    private void lblDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMKMouseClicked
        new ChangePassWord().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDoiMKMouseClicked

    private void btnCapNhatTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTTActionPerformed
        updateTT();
        setFormTT();
    }//GEN-LAST:event_btnCapNhatTTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayerGiaoDien;
    private javax.swing.JButton btnCapNhatTT;
    private javax.swing.JPanel btnDanhGia;
    private javax.swing.JPanel btnDatBan;
    private javax.swing.JButton btnDatBanNgay;
    private javax.swing.JPanel btnDonDat;
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboTimeBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDangXuatXT;
    private javax.swing.JLabel lblDanhGia;
    private javax.swing.JLabel lblDatBan;
    private javax.swing.JLabel lblDoiMK;
    private javax.swing.JLabel lblDondat;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblHeaderTenNhaHang;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLoiChao;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenNH;
    private javax.swing.JLabel lblTenNhaHang;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblXemThem;
    private javax.swing.JPanel pnDangNhap;
    private javax.swing.JPanel pnDangXuat;
    private javax.swing.JPanel pnDangXuatXT;
    private javax.swing.JPanel pnDatBan;
    private javax.swing.JPanel pnDoiMK;
    private javax.swing.JPanel pnFooter;
    private javax.swing.JPanel pnGDDatBan;
    private javax.swing.JPanel pnGiaoDien;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnLeftDB;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnMenuItem;
    private javax.swing.JPanel pnMenuNgang;
    private javax.swing.JPanel pnNhan;
    private javax.swing.JPanel pnQLTaiKhoan;
    private javax.swing.JPanel pnRightDB;
    private javax.swing.JPanel pnThoat;
    private javax.swing.JPanel pnUser;
    private javax.swing.JPanel pnXemThem;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtNgayDat;
    private javax.swing.JTextField txtSoNguoi;
    private javax.swing.JTextField txtTTEmail;
    private javax.swing.JTextField txtTTHoTen;
    private javax.swing.JTextField txtTTNgaySinh;
    private javax.swing.JTextField txtTTSDT;
    private javax.swing.JTextField txtTTUser;
    // End of variables declaration//GEN-END:variables
    private void init() {
        this.setLocationRelativeTo(null);
        //this.setIconImage(ShareHelper.getAppIcon()); 
        if (ShareHelper.USERkh != null) {
            btnUser.setText(ShareHelper.USERkh.getUsername());
            lblTen.setText(ShareHelper.USERkh.getHoTen());
        }

        setFormTT();

        Date date = DateHelper.now();
        lblNgay.setText(DateHelper.toString(date));
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date time = new Date();
                SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss a");
                String text = fm.format(time);
                lblGio.setText(text);
            }
        }).start();
    }

    //Code quan ly thong tin khach hang
    KhachHangDAO daoKH = new KhachHangDAO();

    public void setFormTT() {
        if (ShareHelper.USERkh != null) {
            txtTTUser.setText(ShareHelper.USERkh.getUsername());
            txtTTHoTen.setText(ShareHelper.USERkh.getHoTen());
            rdoNam.setSelected(ShareHelper.USERkh.isGioiTinh());
            rdoNam.setSelected(!(ShareHelper.USERkh.isGioiTinh()));
            txtTTNgaySinh.setText(DateHelper.toString(ShareHelper.USERkh.getNgaySinh()));
            txtTTSDT.setText(ShareHelper.USERkh.getSdt());
            txtTTEmail.setText(ShareHelper.USERkh.getEmail());
        }
    }

    public KhachHang getFormTT() {
        KhachHang model = new KhachHang();
        model.setUsername(txtTTUser.getText());
        model.setHoTen(txtTTHoTen.getText());
        model.setNgaySinh(DateHelper.toDate(txtTTNgaySinh.getText()));  //chuyển char[] thành String
        model.setSdt(txtTTSDT.getText());
        model.setEmail(txtTTEmail.getText());
        model.setGioiTinh(rdoNam.isSelected());
        return model;
    }

    void updateTT() {
        KhachHang model = getFormTT();
        try {
            daoKH.update(model);     //cập nhật nhân viên theo maNV
            ShareHelper.USERkh = model;
            DialogHelper.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");

        }
    }
}
